Fix unused function clear_tuntap warning
This warning was promoted to error in the unit tests, found while
buiding mtu unit tests:

In file included from src/openvpn/route.h:33:0,
                 from src/openvpn/options.h:36,
                 from tests/unit/mtu/test.c:14:
src/openvpn/tun.h:206:13: error: 'clear_tuntap' declared 'static'
but never defined [-Werror=unused-function]