Fix compile warn - missing braces/initializer
This commit fixes the following warning, which is promoted to error in
tests/unit/tls_crypt (gcc 4.4.7):

src/openvpn/crypto_mbedtls.c: In function 'rand_ctx_get':
src/openvpn/crypto_mbedtls.c:248:5: error: missing braces around
        initializer [-Werror=missing-braces]
     static mbedtls_entropy_context ec = {0};
     ^
/home/radu/proj/ovpn/src/openvpn/crypto_mbedtls.c:248:5: error: (near
	initialization for 'ec.accumulator') [-Werror=missing-braces]
cc1: all warnings being treated as errors